/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bear.gltf -T 
Files: bear.gltf [110.44KB] > F:\My Documents\Sites\games\race-game\public\models\bear-transformed.glb [11.01KB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bear-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.character_bear.geometry} material={materials['BrownDark.036']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.character_bearHead.geometry} material={materials['Black.025']} position={[0, 0.704, 0]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/bear-transformed.glb')
