/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const link = `${process.env.NEXT_PUBLIC_CDN}games/Race Game/beach-ball.gltf`

export function BeachBall(props) {
    const { nodes, materials } = useGLTF(link);
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere000.geometry}
                material={materials["White.008"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere000_1.geometry}
                material={materials["Blue.004"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere000_2.geometry}
                material={materials["Red.003"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere000_3.geometry}
                material={materials["Yellow.012"]}
            />
        </group>
    );
}

useGLTF.preload(link);
