/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Hamode (https://sketchfab.com/mohammadzaid.cy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/seating-bleacher-6e0e88fa79c84ae082ef06908ca77650
Title: Seating | Bleacher
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const link = `${process.env.NEXT_PUBLIC_CDN}games/Race Game/bleacher.glb`

export function Bleacher({ rotation, ...props }) {
    const { nodes, materials } = useGLTF(link);
    return (
        <group {...props} dispose={null} rotation={rotation}>

            <group scale={0.0005}>
                {/* Assuming that the original position of the component in the GLTF file is [0, 0, 0] */}
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.bleacher20_Bleacher_0.geometry}
                    material={materials.Bleacher}
                    // scale={0.5}
                    position={[2500, 0, 1000]}  // Adjust this position based on the original position of the component
                />
            </group>
        </group>
    );
}

useGLTF.preload(link);
