/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const link = `${process.env.NEXT_PUBLIC_CDN}games/Race Game/boat.gltf`

export function Boat(props) {
    const { nodes, materials } = useGLTF(link);
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.boat_large_8angles.geometry}
                material={materials.wood}
                position={[1.31, 0, -9.962]}
            />
        </group>
    );
}

useGLTF.preload(link);
