/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useStore } from "@/hooks/useStore";

// const link = `${process.env.NEXT_PUBLIC_CDN}games/Race Game/boat.gltf`
const link = `/models/boat.gltf`

export function Boat(props) {
    const graphicsQuality = useStore((state) => state.graphicsQuality);
    const { nodes, materials } = useGLTF(link);
    const groupRef = useRef();
    const timeRef = useRef(0);
    const phaseRef = useRef(Math.random() * Math.PI * 2);

    useFrame((state, delta) => {
        if (!groupRef.current) return;
        if (graphicsQuality !== "High") return;
        timeRef.current += delta;
        const t = timeRef.current + phaseRef.current;
        // Slow roll side to side
        groupRef.current.rotation.z = Math.sin(t * 0.6) * 0.006;
        // Subtle pitch forward/back
        groupRef.current.rotation.x = Math.sin(t * 0.5 + 1) * 0.002;
    });

    return (
        <group ref={groupRef} {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.boat_large_8angles.geometry}
                material={materials.wood}
                position={[1.31, 0, -9.962]}
            />
        </group>
    );
}

useGLTF.preload(link);
