/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const link = `${process.env.NEXT_PUBLIC_CDN}games/Race Game/BaseCharacter.gltf`
// const link = `https://cdn.articles.media/games/Race Game/BaseCharacter.gltf`

function getRandomDelay() {
    // Generate a random delay between 0 and 500 microseconds (adjust as needed)
    return Math.random() * 500;
}

export default function DefaultPlayerCharacter(props) {

    const group = useRef();
    const { nodes, materials, animations } = useGLTF(link);
    const { actions } = useAnimations(animations, group);

    useEffect(() => {

        console.log("Actions", actions)

        actions.Idle.play();

    }, [actions]);

    useEffect(() => {
        
        // Delay all animations randomly
        Object.values(actions).forEach((action) => {
            setTimeout(() => {
                actions.Idle.play();
            }, getRandomDelay());
        });

    }, [actions]);

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="CharacterArmature">
                    <group name="Body">
                        <skinnedMesh
                            name="Cube004"
                            geometry={nodes.Cube004.geometry}
                            material={materials.Skin}
                            skeleton={nodes.Cube004.skeleton}
                        />
                        <skinnedMesh
                            name="Cube004_1"
                            geometry={nodes.Cube004_1.geometry}
                            material={materials.Face}
                            skeleton={nodes.Cube004_1.skeleton}
                        />
                    </group>
                    <primitive object={nodes.Bone} />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload(link);
