/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const link = `${process.env.NEXT_PUBLIC_CDN}games/Race Game/wind-turbine.gltf`

export function WindTurbine(props) {

    const group = useRef();
    const { nodes, materials, animations } = useGLTF(link);
    const { actions } = useAnimations(animations, group);

    useEffect(() => {

        console.log("Actions", actions)

        if (!props?.disableAnimation) {
            actions.Wind_turbine_001_BladesAction.play();
        }

    }, [actions]);

    // useEffect(() => {
        
    //     // Delay all animations randomly
    //     Object.values(actions).forEach((action) => {
    //         setTimeout(() => {
    //             actions.Idle.play();
    //         }, getRandomDelay());
    //     });

    // }, [actions]);

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="Wind_turbine_001">
                    <mesh
                        name="Wind_turbine_001_Wind_turbine_Circle001"
                        castShadow
                        receiveShadow
                        geometry={nodes.Wind_turbine_001_Wind_turbine_Circle001.geometry}
                        material={materials.gray}
                    />
                    <mesh
                        name="Wind_turbine_001_Wind_turbine_Circle001_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Wind_turbine_001_Wind_turbine_Circle001_1.geometry}
                        material={materials.red}
                    />
                    <group
                        name="Wind_turbine_001_Blades"
                        position={[0.008, 4.384, 0.489]}
                    >
                        <mesh
                            name="Wind_turbine_001_Wind_turbine_Circle000"
                            castShadow
                            receiveShadow
                            geometry={nodes.Wind_turbine_001_Wind_turbine_Circle000.geometry}
                            material={materials.gray}
                        />
                        <mesh
                            name="Wind_turbine_001_Wind_turbine_Circle000_1"
                            castShadow
                            receiveShadow
                            geometry={
                                nodes.Wind_turbine_001_Wind_turbine_Circle000_1.geometry
                            }
                            material={materials.red}
                        />
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload(link);